// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { cookies } from "next/headers";
import { jwtVerify } from "jose";

// ✅ เรียก font loaders ที่ module scope (นอก component) และเก็บใน const
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// สร้าง type ให้ชัด
type Role = "admin" | "customer" | null;
async function getUserRole(): Promise<Role> {
  const token = (await cookies()).get("token")?.value;
  if (!token) return null;

  try {
    const secret = new TextEncoder().encode(process.env.JWT_SECRET!);
    const { payload } = await jwtVerify(token, secret);
    const raw = (payload as any)?.role as unknown;

    // 👇 แคบค่าให้เป็น union ที่ยอมรับเท่านั้น
    if (raw === "admin") return "admin";
    if (raw === "customer") return "customer";
    return null;
  } catch {
    return null;
  }
}
// ⚠️ layout ควรเป็น Server Component (ห้ามใส่ "use client")
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const role = await getUserRole();
  const isAdmin = role === "admin";
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <Navbar /> */}
        {/* {!isAdmin && <Navbar />}  */}
        <Navbar role={role} />
        <main className="md:ml-20">{children}</main>
      </body>
    </html>
  );
}
